name: NBML Validation
on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show repo tree
        run: |
          pwd
          python --version
          ls -la
          find . -maxdepth 3 -type f | sort

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Import validator smoke test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import sys, os
          print("sys.path:", sys.path)
          try:
              import tooling.helix_val as hv
              print("Imported tooling.helix_val OK")
          except Exception as e:
              print("IMPORT ERROR:", e)
              raise SystemExit(1)
          PY

      - name: Validate NBML
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import os
          import tooling.helix_val as hv

          def nbml_files(root):
              for base in ("omu", "datasets", "."):
                  if not os.path.isdir(base):
                      continue
                  for dp,_,fs in os.walk(base):
                      for fn in fs:
                          low = fn.lower()
                          if low.endswith((".nbml.yaml", ".nbml.yml", ".nbml.json")):
                              yield os.path.join(dp, fn)

          found = False
          fails = []
          for path in sorted(nbml_files(".")):
              found = True
              try:
                  doc = hv.load_nbml(path)
                  res = hv.evaluate(doc)
                  print(f"[NBML] {path} :: TOTAL={res['total']} :: "
                        f"struct={'OK' if res['structure_score']['ok'] else 'FAIL'} "
                        f"callbacks={'OK' if res['callback_score']['ok'] else 'FAIL'} "
                        f"arcs={'OK' if res['arc_score']['ok'] else 'FAIL'}")
                  if res["total"] < 70.0 or not all(res[k]["ok"] for k in ("structure_score","callback_score","arc_score")):
                      fails.append((path, res))
              except Exception as e:
                  print(f"[NBML] {path} :: EXCEPTION :: {e}")
                  fails.append((path, {"error": str(e)}))

          if not found:
              print("NOTE: No NBML files found (.nbml.yaml/.json). Succeeding.")
              raise SystemExit(0)

          if fails:
              print("\nValidation failures:")
              for path, res in fails:
                  if isinstance(res, dict) and "total" in res:
                      print(f" - {path} :: TOTAL={res['total']}")
                      for e in res.get("errors", [])[:5]:
                          print("   error:", e)
                      for w in res.get("warnings", [])[:3]:
                          print("   warn :", w)
                  else:
                      print(f" - {path} :: {res}")
              raise SystemExit(1)

          print("All NBML validated.")
          PY
